on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  deploy:
   name: Deployment
   runs-on: ubuntu-latest
   steps:
   - name: Get Latest Code
     uses: actions/checkout@v2
   - name: FTP-Deploy-Action
     uses: SamKirkland/FTP-Deploy-Action@4.1.0
     with:
       server: ${{ secrets.ftp_server }}
       server-dir: html/specht/
       username: ${{ secrets.ftp_username }}
       password: ${{ secrets.ftp_password }}
